<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="diffbot" params="prefix">

  <!-- Define robot constants -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_width" value="0.48"/>
    <xacro:property name="base_length" value="0.54"/>
    <xacro:property name="base_height" value="0.97"/>

    <xacro:property name="lidar_height" value="0.055"/>
    <xacro:property name="lidar_radius" value="0.097"/>

    <xacro:property name="wheel_radius" value="0.08255"/>
    <xacro:property name="wheel_width" value="0.055"/> 

    <xacro:property name="caster_radius" value="0.04"/> 
    <!-- Arbitrary Mass  -->
    <xacro:property name="wheel_mass" value="0.3" />
    <xacro:property name="base_mass" value="0.3" />
    <xacro:property name="caster_wheel_mass" value="0.1" />

    <link name="${prefix}base_footprint"/>

    <link name="${prefix}base_link">
        <collision>
            <origin xyz="0.0 0.0 ${base_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>   
            </geometry>    
        </collision>
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>   
            </geometry>    
            <material name="Wooden">
                <color rgba="0.6 0.3 0.1 1.0"/>
            </material>
            <origin xyz="0.0 0.0 ${base_height/2}"/>
        </visual>
    </link>
    
    <link name="${prefix}lidar_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
            </geometry>
        </collision>
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
            </geometry>
        </visual>
    </link>
    
    <!-- left wheel Link -->
    <link name="${prefix}left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Grey">
            <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" iyz="0.0"
          izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}"/>
        </inertial>
    </link>

    <!-- right wheel Link -->
    <link name="${prefix}right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Grey">
            <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" iyz="0.0"
          izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}"/>
        </inertial>
    </link>

    <!-- caster rear wheel Link -->
    <link name="${prefix}caster_rear_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${caster_wheel_mass}"/>
        <inertia
          ixx="${caster_wheel_mass * 0.4 * (caster_radius * caster_radius)}" ixy="0.0" ixz="0.0"
          iyy="${caster_wheel_mass * 0.4 * (caster_radius * caster_radius)}" iyz="0.0"
          izz="${caster_wheel_mass * 0.4 * (caster_radius * caster_radius)}"/>
        </inertial>
    </link>

    <!-- Joints -->
    <joint name='${prefix}base_to_footprint' type="fixed">
        <parent link="${prefix}base_link"/>
        <child link="${prefix}base_footprint"/>
        <origin xyz="${base_length/2-0.1} 0.0 -${caster_radius*2}"/>
    </joint>

    <joint name="${prefix}base_to_lidar" type="fixed">
        <parent link="${prefix}base_link"/>
        <child link="${prefix}lidar_link"/>
        <origin xyz="${base_length/2-lidar_radius} 0.0 ${base_height + lidar_height/2}" />
    </joint>
    
    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_wheel"/>
      <origin xyz="${base_length/2-0.1} ${base_width/2+wheel_width/2} 0.0" rpy="-1.5708 0.0 0.0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.2"/>
      <limit effort="100" velocity="1.0"/>
    </joint>

    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_wheel"/>
      <origin xyz="${base_length/2-0.1} -${base_width/2+wheel_width/2} 0.0" rpy="-1.5708 0.0 0.0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.2"/>
      <limit effort="100" velocity="1.0"/>
    </joint>

    <joint name="${prefix}caster_rear_wheel_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}caster_rear_wheel"/>
      <origin xyz="-${base_length/2-0.1} 0 -${caster_radius}"/>
    </joint>

    

  </xacro:macro>

</robot>